cookbook/urls.py
"""Defines URL patterns for cookbook"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
    # Page displaying personal homepage for logged-in user,
    url(r'^(?P<username>\w+)/$', views.home_page, name='home_page'),
    # Page listing all of a user's recipes
    url(r'^username/recipes/$', views.recipes, name='recipes'),
    # Pages for each of a user's recipes
    url(r'^recipes/(?P<recipe_id>\d+)/$', views.recipe, name='recipe'),
    # Page for adding a new recipe
    url(r'^new_recipe/$', views.new_recipe, name="new_recipe"),
    # Page for adding a new note
    url(r'^new_note/(?P<recipe_id>\d+)/$', views.new_note, name="new_note"),
    # Page for editting a new note
    url(r'^edit_note/(?P<recipe_id>\d+)/$', views.edit_note, name="edit_note"),
    # Page for editting recipes
    url(r'^edit_recipe/(?P<recipe_id>\d+)/$',
        views.edit_recipe,
        name="edit_recipe"),
]

mise/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'', include(('cookbook.urls', 'cookbook'), namespace='cookbook')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    # Login page using Django's default login view (not views.login)
    url(r'^login/$', login, {'template_name': 'users/login.html'},
    name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

cookbook/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Recipe(models.Model):
    """A recipe the user wants to record"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, models.CASCADE)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text


class Note(models.Model):
    """Things to note about the dish or recipe"""
    recipe = models.ForeignKey(Recipe, models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

    # class Meta:
    #     verbose_name_plural = 'entries'


class Ingredient(models.Model):
    """Ingredients required for the recipe"""
    recipe = models.ForeignKey(Recipe, models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text


class Step(models.Model):
    """Cooking steps for the recipe"""
    recipe = models.ForeignKey(Recipe, models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text

cookbook/forms.py
from django import forms
from .models import Recipe, Note, Ingredient


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['text']
        labels = {'text': ''}


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class EditNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        exclude = ()

    NoteFormSet = forms.inlineformset_factory(
        Recipe, Note, fields=('text',), extra=3)

cookbook/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django import forms

from .models import Recipe, Note, Ingredient, Step
from .forms import RecipeForm, NoteForm

# Relevant Functions


# Make sure the recipe belongs to the current user
def check_recipe_owner(recipe, request):
    if recipe.owner != request.user:
        raise Http404


# Create your views here.
def index(request):
    # If already logged in, redirect to user pages
    if request.user.is_authenticated:
        return HttpResponseRedirect(
            reverse(
                'cookbook:home_page',
                kwargs={
                    'username': request.user.username
                }))
    """The landing page for mise"""
    return render(request, 'cookbook/index.html')


@login_required
def home_page(request, username):
    """Home page for logged in users"""
    return render(request, 'cookbook/home_page.html')


@login_required
def recipes(request):
    """Show all recipes"""
    recipes = Recipe.objects.filter(owner=request.user).order_by('date_added')
    context = {'recipes': recipes}
    return render(request, 'cookbook/recipes.html', context)


@login_required
def recipe(request, recipe_id):
    """Show a single recipe and all its steps"""
    recipe = get_object_or_404(Recipe, id=recipe_id)
    check_recipe_owner(recipe, request)

    notes = recipe.note_set.all()
    ingredients = recipe.ingredient_set.order_by('-date_added')
    steps = recipe.step_set.order_by('-date_added')

    context = {
        'recipe': recipe,
        'notes': notes,
        'ingredients': ingredients,
        'steps': steps
    }
    return render(request, 'cookbook/recipe.html', context)


@login_required
def new_recipe(request):
    """Add a new recipe"""
    # Rather than just = 'GET', it is safe to return a blank form for any other
    # request as well
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = RecipeForm()
    else:
        # POST data submitted; process data
        form = RecipeForm(request.POST)
        if form.is_valid():
            new_recipe = form.save(commit=False)
            new_recipe.owner = request.user
            new_recipe.save()
            return HttpResponseRedirect(reverse('cookbook:recipes'))

    context = {'form': form}
    return render(request, 'cookbook/new_recipe.html', context)


@login_required
def new_note(request, recipe_id):
    """Add a new note to a recipe"""
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if request.method != 'POST':
        # No data submitted; create a blank form
        form = NoteForm()
    else:
        # POST data submitted; process data
        form = NoteForm(data=request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.recipe = recipe
            new_note.save()
            return HttpResponseRedirect(
                reverse('cookbook:recipe', args=[recipe_id]))

    context = {'recipe': recipe, 'form': form}
    return render(request, 'cookbook/new_note.html', context)


@login_required
def edit_note(request, recipe_id):
    """Edit an existing note"""
    recipe = Recipe.objects.get(pk=recipe_id)
    NoteInlineFormSet = forms.inlineformset_factory(
        Recipe, Note, fields=('text', ))
    check_recipe_owner(recipe, request)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current note
        formset = NoteInlineFormSet(instance=recipe)
    else:
        # POST data submitted; process data
        formset = NoteInlineFormSet(
            request.POST, request.FILES, instance=recipe)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect(
                reverse('cookbook:recipe', args=[recipe.id]))

    context = {'recipe': recipe, 'formset': formset}
    return render(request, 'cookbook/edit_note.html', context)


# Test development of html forms for editting recipe
@login_required
def edit_recipe(request, recipe_id):
    """Show a single recipe and all its steps"""
    recipe = get_object_or_404(Recipe, id=recipe_id)
    check_recipe_owner(recipe, request)

    ingredients = recipe.ingredient_set.all()
    notes = recipe.note_set.order_by('-date_added')
    steps = recipe.step_set.order_by('-date_added')

    if request.method != 'POST':
        # Initial request; pre-fill form with the current queryset
        context = {
            'recipe': recipe,
            'notes': notes,
            'ingredients': ingredients,
            'steps': steps
        }
        return render(request, 'cookbook/edit_recipe.html', context)
    else:
        # POST data submitted; process data
        context = {
            'recipe': recipe,
            'notes': notes,
            'ingredients': ingredients,
            'steps': steps
        }
        return render(request, 'cookbook/edit_recipe.html', context)

cookbook/templates/cookbook/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Mise</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>

    <!-- Static navbar -->
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
            </button>
          <a class="navbar-brand" href="{% url 'cookbook:index' %}">
            Mise
          </a>
          </div>

          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'cookbook:recipes' %}">Recipes</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><a>Hello, {{ user.username }}.</a></li>
                <li><a href="{% url 'users:logout' %}">logout</a></li>
              {% else %}
                <li><a href="{% url 'users:register' %}">register</a></li>
                <li><a href="{% url 'users:login' %}">log in</a></li>
              {% endif %}
            </ul>
          </div><!--/.nav-collapse-->

        </div>
      </nav>

      <div class="container">

        <div class="page-header">
          {% block header %}
          {% endblock header %}
        </div>
        <div>
          {% block content %}
          {% endblock content %}
        </div>

      </div><!-- /container -->
  </body>

cookbook/templates/cookbook/edit_note.html
{% extends "cookbook/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2><a href="{% url 'cookbook:recipe' recipe.id %}">{{ recipe }}</a></h2>
{% endblock header %}

{% block content %}

    <p>Edit note:</p>
    <form action="{% url 'cookbook:edit_note' recipe.id %}" method='post' class='form'>
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

cookbook/templates/cookbook/edit_recipe.html
{% extends 'cookbook/base.html' %} {% load static %} {% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'cookbook/css/recipe_style.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Lato:100,300,400" rel="stylesheet">
<h2>{{ recipe }}</h2>
{% endblock header %} {% block content %}

<div class="section-name">
    Ingredients
    <br>
</div>
<form action="{% url 'cookbook:edit_recipe' recipe.id %}" method="post" class="form">
    {% for ingredient in ingredients %} {% csrf_token %}
    <input type="text" value="{{ ingredient.text }}" name="ingredient">
    <br> {% endfor %}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>



<div class="section-name">
    Directions
</div>
{% for step in steps %}
<div id="step">
    {{ step.text|linebreaks }}
</div>
{% endfor %}

<p>
    <a href="{% url 'cookbook:new_note' recipe.id %}">add new note</a>
    <a href="{% url 'cookbook:edit_note' recipe.id %}">edit notes</a>
</p>

{% for note in notes %}
<div class="panel-body">
    {{ note.text|linebreaks }}
</div>
</div>
<!-- panel -->

{% empty %} There are no entries for this post yet. {% endfor %} {% endblock content %}

cookbook/templates/cookbook/home_page.html
{% extends "cookbook/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>
    <a href="{% url 'cookbook:recipes' %}">Recipes</a>
</h2>
{% endblock header %}

cookbook/templates/cookbook/index.html
{% load static %}

<head>
<link rel="stylesheet" type="text/css" href="{% static 'cookbook/css/style.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Lato:100,300,400" rel="stylesheet">

<title>Mise</title>
</head>

<body style="background-image: url('{% static "cookbook/img/bg0.jpg" %}')";>
    <div class="bg-overlay">
        <div class="wrapper">
            <div class="header">
                <a href="{% url 'cookbook:index' %}">MISE</a>
                <a href="{% url 'cookbook:recipes' %}">RECIPES</a>
                <a href="{% url 'users:login' %}">LOG IN</a>
            </div>
            <div class="main">
                <div id="name"> MISE </div>
                <div id="slogan"> ITERATIVE RECIPE DEVELOPMENT </div>
            </div>
        </div>
    </div>
</body>

cookbook/templates/cookbook/new_note.html
{% extends "cookbook/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2><a href="{% url 'cookbook:recipe' recipe.id %}">{{ recipe }}</a></h2>
{% endblock header %}

{% block content %}

    <p>Add a new note:</p>
    <form action="{% url 'cookbook:new_note' recipe.id %}" method='post' class = "form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add note</button>
        {% endbuttons %}
    </form>

{% endblock content %}

cookbook/templates/cookbook/new_recipe.html
{% extends "cookbook/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

  <p>Add a new recipe:</p>
  <form action="{% url 'cookbook:new_recipe' %}" method='post'>
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
      {% endbuttons %}

  </form>

{% endblock content %}

cookbook/templates/cookbook/recipe.html
{% extends 'cookbook/base.html' %}
{% load static %}

{% block header %}
  <link rel="stylesheet" type="text/css" href="{% static 'cookbook/css/recipe_style.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400" rel="stylesheet">
  <h2>{{ recipe }}</h2>
{% endblock header %}

{% block content %}

<div class="section-name">
    Ingredients
</div>
  {% for ingredient in ingredients %}
    <div id="ingredient">
      {{ ingredient.text|linebreaks }}
    </div>
  {% endfor %}


  <div class="section-name">
    Directions
  </div>
  {% for step in steps %}
  <div id="step">
    {{ step.text|linebreaks }}
  </div>
  {% endfor %}

  <p>
    <a href="{% url 'cookbook:new_note' recipe.id %}">add new note</a>
  </p>

  {% for note in notes %}
      <div class="panel-body">
        {{ note.text|linebreaks }}
      </div>
    </div> <!-- panel -->

  {% empty %}
      There are no entries for this post yet.
  {% endfor %}

{% endblock content %}

cookbook/templates/cookbook/recipes.html
{% extends "cookbook/base.html" %}

{% block header %}
  <h1>Recipes</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for recipe in recipes %}
      <li>
        <h3>
          <a href="{% url 'cookbook:recipe' recipe.id %}">
            {{ recipe }}
          </a>
        </h3>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'cookbook:new_recipe' %}">Add a new recipe</h3>
{% endblock content %}